library(pacman)
# p_load(tidyverse,leaflet,scales,clipr,skimr,DataExplorer)
# source('c:/temp/myconfig.r',encoding = 'UTF-8')
library(tidyverse)
library(leaflet)
library(scales)
library(clipr)
library(skimr)
library(DataExplorer)
library(ggthemes)
library(paletteer)
windowsFonts(ng = windowsFont('NanumGothic'))
